### ISSUE TITLE
On-chain referral Scheme

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/roadmap#71]
## On-chain referral Scheme

The introduction of the on-chain referral program is to allow functionality in the protocol to incentivise users and community members to refer new traders by voting to provide benefits for referrers and/or referees. Whilst a referral program is active, referrers will receive a proportion of all referee taker fees as a reward and referees will receive a discount on any taker fees.

To see more on this feature check out the [spec](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0083-RFPR-on_chain_referral_program.md)

**Comment by candida-d** [comment]
Closed as a duplicate of https://github.com/vegaprotocol/roadmap/issues/64
